export const schedules = {
  // DAY-MONTH-YEAR
  '2022-12-01': [
    {
      id: 'fgasd',
      collector: 'Adam',
      status: 'active',
      time: '1669852800',
      collections: [
        {
          id: 'fgasd-1',
          location: {
            street: '1 High Street',
            city: 'Sheffield',
            county: 'South Yorkshire',
            postcode: 'S1 2BJ',
          },
          date: '2022-12-01',
          time: '1669852800',
          status: 'active',
          canReschedule: true,
        },
        {
          id: 'fgasd-2',
          location: {
            street: '1 High Street',
            city: 'Sheffield',
            county: 'South Yorkshire',
            postcode: 'S1 2BJ',
          },
          date: '2022-12-01',
          time: '1669856400',
          status: 'active',
          canReschedule: false,
        },
      ],
    },
    {
      id: 'kiju',
      collector: 'Adam',
      status: 'delayed',
      time: '1669863600',
      collections: [
        {
          id: 'kiju-1',
          location: {
            street: '1 High Street',
            city: 'Sheffield',
            county: 'South Yorkshire',
            postcode: 'S1 2BJ',
          },
          date: '2022-12-01',
          time: '1669863600',
          status: 'active',
          canReschedule: true,
        },
        {
          id: 'kiju-2',
          location: {
            street: '1 High Street',
            city: 'Sheffield',
            county: 'South Yorkshire',
            postcode: 'S1 2BJ',
          },
          date: '2022-12-01',
          time: '1669867200',
          status: 'delayed',
          canReschedule: true,
        },
      ],
    },
    {
      id: 'adefg',
      collector: 'Alice',
      status: 'active',
      time: '1669867200',
      collections: [
        {
          id: 'adefg-1',
          location: {
            street: '1 High Street',
            city: 'Sheffield',
            county: 'South Yorkshire',
            postcode: 'S1 2BJ',
          },
          date: '2022-12-01',
          time: '1669867200',
          status: 'active',
          canReschedule: false,
        },
        {
          id: 'adefg-2',
          location: {
            street: '1 High Street',
            city: 'Sheffield',
            county: 'South Yorkshire',
            postcode: 'S1 2BJ',
          },
          date: '2022-12-01',
          time: '1669870800',
          status: 'active',
          canReschedule: false,
        },
      ],
    },
    {
      id: 'lsyc',
      collector: 'Adam',
      status: 'delayed',
      time: '1669874400',
      collections: [
        {
          id: 'lsyc-1',
          location: {
            street: '1 High Street',
            city: 'Sheffield',
            county: 'South Yorkshire',
            postcode: 'S1 2BJ',
          },
          date: '2022-12-01',
          time: '1669874400',
          status: 'active',
          canReschedule: true,
        },
        {
          id: 'lsyc-2',
          location: {
            street: '1 High Street',
            city: 'Sheffield',
            county: 'South Yorkshire',
            postcode: 'S1 2BJ',
          },
          date: '2022-12-01',
          time: '1669878000',
          status: 'delayed',
          canReschedule: false,
        },
      ],
    },
    {
      id: 'lonh',
      collector: 'Adam',
      status: 'inactive',
      time: '1669860000',
      collections: [
        {
          id: 'lonh-1',
          location: {
            street: '1 High Street',
            city: 'Sheffield',
            county: 'South Yorkshire',
            postcode: 'S1 2BJ',
          },
          date: '2022-12-01',
          time: '1669860000',
          status: 'inactive',
          canReschedule: false,
        },
        {
          id: 'lonh-2',
          location: {
            street: '1 High Street',
            city: 'Sheffield',
            county: 'South Yorkshire',
            postcode: 'S1 2BJ',
          },
          date: '2022-12-01',
          time: '1669863600',
          status: 'inactive',
          canReschedule: false,
        },
      ],
    },
    {
      id: 'polk',
      collector: 'Alice',
      status: 'inactive',
      time: '1669860000',
      collections: [
        {
          id: 'polk-1',
          location: {
            street: '1 High Street',
            city: 'Sheffield',
            county: 'South Yorkshire',
            postcode: 'S1 2BJ',
          },
          date: '2022-12-01',
          time: '1669860000',
          status: 'inactive',
          canReschedule: true,
        },
        {
          id: 'polk-2',
          location: {
            street: '1 High Street',
            city: 'Sheffield',
            county: 'South Yorkshire',
            postcode: 'S1 2BJ',
          },
          date: '2022-12-01',
          time: '1669863600',
          status: 'inactive',
          canReschedule: true,
        },
      ],
    },
    {
      id: 'dwqdd',
      collector: 'Nathan',
      status: 'inactive',
      time: '1669874400',
      collections: [
        {
          id: 'dwqdd-1',
          location: {
            street: '1 High Street',
            city: 'Sheffield',
            county: 'South Yorkshire',
            postcode: 'S1 2BJ',
          },
          date: '2022-12-01',
          time: '1669874400',
          status: 'inactive',
          canReschedule: true,
        },
        {
          id: 'dwqdd-2',
          location: {
            street: '1 High Street',
            city: 'Sheffield',
            county: 'South Yorkshire',
            postcode: 'S1 2BJ',
          },
          date: '2022-12-01',
          time: '1669878000',
          status: 'inactive',
          canReschedule: true,
        },
      ],
    },
    {
      id: 'drfg',
      collector: 'Nathan',
      status: 'active',
      time: '1669903200',
      collections: [
        {
          id: 'drfg-1',
          location: {
            street: '1 High Street',
            city: 'Sheffield',
            county: 'South Yorkshire',
            postcode: 'S1 2BJ',
          },
          date: '2022-12-01',
          time: '1669903200',
          status: 'active',
          canReschedule: true,
        },
        {
          id: 'drfg-2',
          location: {
            street: '1 High Street',
            city: 'Sheffield',
            county: 'South Yorkshire',
            postcode: 'S1 2BJ',
          },
          date: '2022-12-01',
          time: '1669906800',
          status: 'active',
          canReschedule: true,
        },
      ],
    },
    {
      id: 'juyj',
      collector: 'Alex',
      status: 'inactive',
      time: '1669903200',
      collections: [
        {
          id: 'juyj-1',
          location: {
            street: '1 High Street',
            city: 'Sheffield',
            county: 'South Yorkshire',
            postcode: 'S1 2BJ',
          },
          date: '2022-12-01',
          time: '1669903200',
          status: 'inactive',
          canReschedule: false,
        },
        {
          id: 'juyj-2',
          location: {
            street: '1 High Street',
            city: 'Sheffield',
            county: 'South Yorkshire',
            postcode: 'S1 2BJ',
          },
          date: '2022-12-01',
          time: '1669906800',
          status: 'inactive',
          canReschedule: false,
        },
      ],
    },
    {
      id: 'fwrs',
      collector: 'Alex',
      status: 'delayed',
      time: '1669914000',
      collections: [
        {
          id: 'fwrs-1',
          location: {
            street: '1 High Street',
            city: 'Sheffield',
            county: 'South Yorkshire',
            postcode: 'S1 2BJ',
          },
          date: '2022-12-01',
          time: '1669874400',
          status: 'delayed',
          canReschedule: false,
        },
        {
          id: 'fwrs-2',
          location: {
            street: '1 High Street',
            city: 'Sheffield',
            county: 'South Yorkshire',
            postcode: 'S1 2BJ',
          },
          date: '2022-12-01',
          time: '1669917600',
          status: 'delayed',
          canReschedule: true,
        },
      ],
    },
  ],
  '2022-12-02': [
    {
      id: 'fgasd',
      collector: 'Adam',
      status: 'active',
      time: '1669957200',
    },
    {
      id: 'fhedr',
      collector: 'Adam',
      status: 'delayed',
      time: '1669971600',
    },
    {
      id: 'juyjg',
      collector: 'Alex',
      status: 'active',
      time: '1669986000',
    },
    {
      id: 'fwrsd',
      collector: 'Alex',
      status: 'delayed',
      time: '1670000400',
    },
  ],
  '2022-12-03': [
    {
      id: 'fgasd',
      collector: 'Adam',
      status: 'active',
      time: '1670050800',
    },
    {
      id: 'fhedr',
      collector: 'Adam',
      status: 'delayed',
      time: '1670065200',
    },
  ],
};
